name: InfernoAI CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install build tools
      run: |
        sudo apt-get install -y build-essential

    - name: Build InfernoAI Library
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run InfernoAI Tests
      run: |
        cd build
        ./run_tests
