name: A

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: cmake/setup-cmake@v3
      with:
        cmake-version: '3.24'  # Specify the CMake version you need

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build C++ Library
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run C++ Tests
      run: |
        cd build
        ./run_tests
