name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: cmake-bazel@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build C++ Library
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run C++ Tests
      run: |
        cd build
        ./run_tests
